name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v
  check-runner:
    runs-on: ubuntu-latest
    steps:
      - run: whoami
      - run: echo "hello world"
  login-dev-server:
    runs-on: ubuntu-latest
    enviroment:
      name: development
    steps:
    - name: login to dev server
      uses: appleboy/ssh-action@v0.1.10
      with:
 	host: ${{ env.DEV_HOST }}
	username: lab01
	password: ${{ secrets.DEV_PASS }}
      run: |
	 echo "hello world"
      	 ls -al
      	 whoami



