name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  login-dev-server:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - run: |
          echo ${{ env.DEV_HOST }}
          echo ${{ secrets.DEV_PASS}}
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.DEV_HOST }}
          username: github-cicd
          password: ${{ secrets.DEV_PASS }}
          script: |
            whoami
            ls -al
            export ${{ vars.GIT_SSH_COMMAND }}
            cd ${{vars.WORKING_DIR }} && git pull origin develop \
            /edx/app/edxapp/venvs/edxapp/bin/i18n_tool extract  && \
            /edx/app/edxapp/venvs/edxapp/bin/i18n_tool generate
            cd /edx/app/edxapp/edx-platform && \
            /edx/app/edxapp/venvs/edxapp/bin/python manage.py lms compilejsi18n && \
            /edx/app/edxapp/venvs/edxapp/bin/python manage.py cms compilejsi18n
            /edx/bin/edxapp-update-assets
            /edx/bin/supervisorctl restart lms
