name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  login-dev-server:
    runs-on: ubuntu-latest
    environment:
      name: development
    steps:
      - name: Pull code
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.DEV_HOST }}
          username: github-cicd
          password: ${{ secrets.DEV_PASS }}
          script: |
            sudo su edxapp -s /bin/bash
            whoami
            cd ${{vars.WORKING_DIR }} && git pull origin develop
      - name: Deploy dev server
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ vars.DEV_HOST }}
          username: github-cicd
          password: ${{ secrets.DEV_PASS }}
          script: |
            ls -al
            cd /edx/app/edxapp/edx-platform && \
            ls -al && \
            source /edx/app/edxapp/venvs/edxapp && \
            /edx/app/edxapp/venvs/edxapp/bin/i18n_tool extract  && \
            /edx/app/edxapp/venvs/edxapp/bin/i18n_tool generate && \
            /edx/app/edxapp/venvs/edxapp/bin/python manage.py lms compilejsi18n && \
            /edx/app/edxapp/venvs/edxapp/bin/python manage.py cms compilejsi18n
            if [ $? -eq 0 ]; then
              /edx/bin/edxapp-update-assets
              /edx/bin/supervisorctl restart lms
            else
              echo "Compile i18n failed" && exit 1
            fi
