name: sync-specific-folder
run-name: ${{ github.actor }} is running sync folder
on:
  push:
    branches:
      - main
    paths:
      - templates/**
  # pull_request_target:
  #   branches:
  #     - main
  #   types: [labeled]
  #   paths:
  #     - templates/**
jobs:
  sync-branch:
    if: ${{ github.event.pull_request.merged }} == true && ${{ github.event.pull_request.labels.*.name }} =~ 'sync-branch'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: sync branch
      run: |
          echo ${{github.event.pull_request.labels.*.name}}
          # git checkout sync-branch
          # git checkout -- templates # Reset the templates folder to the state of the 'theme' branch
          # git checkout main
          # git checkout -- templates # Update the templates folder from the 'theme' branch
          # git add templates
          # git commit -m "Update templates folder in theme1 branch"
          # git push origin sync-branch
