name: sync-specific-folder
run-name: ${{ github.actor }} is running sync folder
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed

jobs:
  sync-branch:
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'sync-branch')
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout node
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: sync site branch with change of merge commit
        run: |
            # echo ${{ toJSON(github.event.pull_request)}}
            git branch
            commit_hash=${{ github.event.pull_request.merge_commit_sha }}
            IFS="," read -r -a branches <<< ${{ vars.SITE_BRANCHES }}

            # Loop through the array elements
            for element in "${branches[@]}"
            do
                echo "Start sync branch: $element"
                git checkout "$element"
                git cherry-pick -m 1 "$commit_hash" > /dev/null 2>&1
                # # Check if cherry-pick was successful
                if [ $? -eq 0 ]; then
                    git push origin "$element"
                    echo "Success sync branch $element!"
                else
                    git cherry-pick --abort
                    echo "Failed sync branch $element!"
                fi
            done
