name: sync-specific-folder
run-name: ${{ github.actor }} is running sync folder
on:
  pull_request_target:
    branches:
      - main
    types: [labeled]
jobs:
  sync-branch:
    if: ${{ github.event.label.name == 'sync-branch' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
