name: sync-specific-folder
run-name: ${{ github.actor }} is running sync folder
on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main

jobs:
  sync-branch:
    # if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'sync-branch')
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Checkout node
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: sync site branch with change of merge commit
        run: |
            git branch
            # commit_hash=${{ github.event.pull_request.base.sha }}
            commit_hash=dc40a099a7e98bdd2791ab583f912143332f34e6
            IFS="," read -r -a branches <<< ${{ vars.SITE_BRANCHES }}

            # Loop through the array elements
            for branch in "${branches[@]}"
            do
                echo "Start sync branch: $branch"
                git checkout "$branch"
                git cherry-pick -m 1 "$commit_hash"
                cherry_pick_status=$?
                # Handle the cherry pick result
                if [ $cherry_pick_status -eq 0 ]; then
                  echo "Cherry pick successful on $branch"
                else
                  echo "Cherry pick failed on $branch"
                  # exit 1
                fi
                continue-on-error: true
            done
